export const API_URL = process.env['NEXT_PUBLIC_API_URL'] || 'http://localhost:8000'
export const FIREBASE_API_KEY = process.env['NEXT_PUBLIC_FIREBASE_API_KEY'] || ''
export const FIREBASE_APP_NAME = process.env['NEXT_PUBLIC_FIREBASE_APP_NAME'] || ''
export const FIREBASE_APP_ID = process.env['NEXT_PUBLIC_FIREBASE_APP_ID'] || ''
export const FIREBASE_SENDER_ID = process.env['NEXT_PUBLIC_FIREBASE_SENDER_ID'] || ''
